### ISSUE TITLE
available when it's not available

### ISSUE THREAD

**Issue by vvt2x** [suegdu/DSV#1]
![unknown_2023 06 18-19 59](https://github.com/suegdu/DSV/assets/136931870/6c2d1be3-2c17-444a-87aa-0a7d6612c15e)
it say 

'warrfye5' available.
[!] 'ga5' available.
[!] '6cc' available.
[!] 'v2p' available.

and they are not even available only the first one how do i fix it

**Comment by suegdu** [comment]
did your account receive the username update change? if yes, then if you have some time i would appreciate to check the <a href="https://github.com/suegdu/DSV#notes">Notes on the repository.</a>

**Comment by vvt2x** [comment]
> 
 yes i have the new  username update change

**Comment by vvt2x** [comment]
in other checker it work only this one it won't

**Comment by suegdu** [comment]
I'll check it and as i stated before it was written poorly and not tested that much thank you, keep up with the updates

**Comment by vvt2x** [comment]
your checker is fast and good keep up the good work, i will <3

**Comment by suegdu** [comment]
thanks

**Comment by suegdu** [comment]
can you provide me with one of those checkers that works with you? @vvt2x

**Comment by vvt2x** [comment]
> can you provide me with one of those checkers that works with you? @vvt2x

sure

**Comment by vvt2x** [comment]
https://github.com/FR12Gimenez/discord-username-checker.git

**Comment by vvt2x** [comment]
this one

**Comment by vvt2x** [comment]
but it's slow

**Comment by suegdu** [comment]
Thank you

**Comment by vvt2x** [comment]
np

**Comment by suegdu** [comment]
Fixed it. updating files now

**Comment by vvt2x** [comment]
i will try it

**Comment by suegdu** [comment]
Keep in mind that the more delay you put the less chance on getting your account suspended, other checkers might be slow but it is for your good.

**Comment by vvt2x** [comment]
the old checker was like every 5 sec

**Comment by suegdu** [comment]
It depends on you but my suggestion is keep the delay decent to avoid suspension. Thank you for your feedback and share the repo with others if you could,

**Comment by vvt2x** [comment]
it work but how do i change the delay

**Comment by vvt2x** [comment]
which one

 }
       response = requests.patch(URL, headers=HEADERS, data=json.dumps(body))
       if response.status_code == 429:
           sleep_time = response.json()["retry_after"]
           print(f"{Lb}[!]{Fore.RED} Rate limit hit. Sleeping for {sleep_time}s")
           time.sleep(sleep_time)
           available_usernames.append(usernames)
       if 'errors' in response.json() :
        if 'username' in response.json()['errors']:
           print(f"{Lb}[!]{Fore.RED} '{usernames}' taken.")
        else :
           print(f"{Lb}[!]{Fore.LIGHTGREEN_EX} '{usernames}' available.")
       else:
           print(f"{Lb}[!]{Fore.RED} Error validating '{usernames}': {response.json()['message']}")
           input(f"{Fore.YELLOW}Press Enter to exit.")
           sys.exit(0)

**Comment by suegdu** [comment]
You can find the delay on line: 143

**Comment by vvt2x** [comment]
ohh shit mb

**Comment by vvt2x** [comment]
soo higher faster lower slower right?

**Comment by suegdu** [comment]
wait i must add another delay because the delay only works with the option 1

**Comment by vvt2x** [comment]
ok ok

**Comment by suegdu** [comment]
I updated it now there are two delays one for option 1 and another one for option 2 you find them on line `144` and line `67`

**Comment by vvt2x** [comment]
ty <3 for the good work

**Comment by suegdu** [comment]
You know what i just created a variable that you can edit it's called `Delay` you just change the number and it will apply
