### ISSUE TITLE
Saying every name is available

### ISSUE THREAD

**Issue by zekepetherick** [suegdu/DSV#6]
When I run the code and I choose the option to check my own usernames.txt list it says every name in that txt is available when it's not, and yes the token that I am using has the username update and is not hitting the api limit because it says available after the first username.

**Comment by suegdu** [comment]
I'll look into it

**Comment by suegdu** [comment]
Do you only face this issue when checking from a list?

**Comment by zekepetherick** [comment]
Yes.

**Comment by suegdu** [comment]
So the option 1 works just fine?

**Comment by zekepetherick** [comment]
Yes, that one works perfectly fine. It's only when I use the option 2 to check my own list of usernames is when I face the issue.

**Comment by suegdu** [comment]
Thank you for your feedback

**Comment by zekepetherick** [comment]
No problem.

**Comment by suegdu** [comment]
Fixed.

**Comment by suegdu** [comment]
Don't forget to drop a star if you could,

**Comment by suegdu** [comment]
As far as my understanding goes, it was a mistyped variable position where is was `usernames` which is the list of usernames and it was supposed to be `username` which is the each of usernames in the list inside the `for` loop
